joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 100

# TCP_controller_x:
#   type: "TCP_controllers/JointVelocityController"
#   joint: q1

position_controller_q1:
  type: "position_controllers/JointPositionController"
  joint: q1

position_controller_q2:
  type: "position_controllers/JointPositionController"
  joint: q2

position_controller_q3:
  type: "position_controllers/JointPositionController"
  joint: q3
